modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="mystic_runestones"
version="1.0"
displayName="Mystic RuneStones"
credits="https://discord.gg/eCAHRcTYc9"
displayURL="https://discord.gg/eCAHRcTYc9"
updateJSONURL="https://discord.gg/eCAHRcTYc9"
logoFile="logo.png"
authors="The_WereF0X"
description="Adds Magic Wands with different abilities"

[[dependencies.mystic_runestones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




